### ISSUE TITLE
Baseline reforms break net income table

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#1016]
For example https://policyengine.org/us/household?gov_irs_income_bracket_rates_1=10&baseline_gov_irs_income_bracket_rates_1=13 gets stuck on Calculating reform impact...

The graph works and the net income table works with non-baseline reforms

**Comment by nikhilwoodruff** [comment]
Hmm I can't reproduce yet (from mobile), the table generates for me

**Comment by MaxGhenis** [comment]
Huh yeah working for me now too...will reopen if it comes back
