### ISSUE TITLE
Fix server debugging bug

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#110]
For me, when I run `make debug-server`, the initialisation runs twice for some reason, causing the second try to fail silently. This is fixed by adding a space (or any change) then removing to any Python file in the server (e.g. app.py), causing Flask to reload and only initialise once this time.

**Comment by MaxGhenis** [comment]
Is this still an issue?

**Comment by nikhilwoodruff** [comment]
Not any more I think. Closing
