### ISSUE TITLE
Accounting view

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#128]

**Comment by nikhilwoodruff** [comment]
## A first draft

![image](https://user-images.githubusercontent.com/35577657/140573745-a5e6ad55-447a-435e-bf82-29369a6b7dc4.png)

Any feedback is welcome on the UI front!

**Comment by MaxGhenis** [comment]
Looks great! A few minor suggestions:
1. Round to the pound
2. Add a column for the delta
3. Make tax values negative instead of putting `-` in the tax rows
4. Indent each level
5. Maybe remove the pound sign and move to the column headers?

**Comment by nikhilwoodruff** [comment]
> Looks great! A few minor suggestions:
> 
> 1. Round to the pound
> 2. Add a column for the delta
> 3. Make tax values negative instead of putting `-` in the tax rows
> 4. Indent each level
> 5. Add comma thousands separator
> 6. Maybe remove the pound sign and move to the column headers?

Thanks! Here's how it looks (ignoring the slight indentation misalignment on level 3):
![image](https://user-images.githubusercontent.com/35577657/140577922-f320e75c-813f-4c80-abd8-8fdc207c7209.png)

**Comment by nikhilwoodruff** [comment]
OK, next challenge (I may have been slightly eager to see how this looks): any ideas for clear presentation of the derivatives/MTRs?
![image](https://user-images.githubusercontent.com/35577657/140579594-8e037605-6fc9-4d4a-a897-623d1b139562.png)

**Comment by nikhilwoodruff** [comment]
We could try and phrase it in terms of MTRs, but I'm just trying to think of the logic necessary:
![image](https://user-images.githubusercontent.com/35577657/140580301-86250463-2c92-45f3-8231-6306dc798107.png)
e.g. this would need to treat separately:
* variables which are directly increased by employment income (e.g. market income)
* variables which are not directly increased by employment income but do react (income tax)

**Comment by MaxGhenis** [comment]
I think the simplest approach for now is to display it as MTRs and not show anything for market income. This would align it with the MTR chart.

I'd also suggest showing MTR diffs in pp as the chart hovercards do.

**Comment by MaxGhenis** [comment]
Done!
