### ISSUE TITLE
Add deep poverty to poverty chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#181]
as a grouped bar chart like this from the blank slate paper
![image](https://user-images.githubusercontent.com/6076111/131175611-f723b9d5-cc2e-40e2-aa26-02c78a0fb93d.png)

**Comment by MaxGhenis** [comment]
@nikhilwoodruff what's the deep poverty rate with the new weighting?

**Comment by nikhilwoodruff** [comment]
2.6% right now (15.9% overall poverty rate) in 2022.

**Comment by MaxGhenis** [comment]
Ok that seems still worth including this chart for then. Thanks.
