### ISSUE TITLE
Abolishing the UC disability element raises an error

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#190]
E.g. https://policyengine.org/uk/population-impact?abolish_UC_disability=1

GCP shows the likely error message (this is the only error we're seeing for the site):
`AttributeError: 'NoneType' object has no attribute 'clone'`

I suspect the parameter `abolish_UC_disability` has an incorrectly named `variable` field.

**Comment by MaxGhenis** [comment]
No longer an issue
