### ISSUE TITLE
Parameter scale component

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#206]
Many of the parameters in OpenFisca country models are `ParameterScales` (a special case of `Parameter`). Instead of a normal parameter, which is essentially a function `f(time) -> value`, a parameter scale defines `f(time, input) -> value`. OpenFisca itself has a few special types of parameter scale:
1. One that applies marginal rates
2. One that selects a specific value for different regions

For example, if we defined the marginal rates (0-20k -> 0.2, 20k+ -> 0), and an input of 30k, a) would result in 4k and b) would result in 0.

Right now, all parameters are surfaced using the `Parameter` component, and parameter scale parameters are surfaced by showing the rates and thresholds individually. It'd be really useful to have a parameter scale component, that shows the parameter scale parameters in a grouped way, and allows the user to add or remove bands.

### In practise

On the client side, we just need a React component to display the existing parameters, as well as +/- buttons that disable when necessary. On the server side, we'll need to decode the policy parameters passed to decide which rates/thresholds to change, which to add and which to remove. I think the cleanest way to do this is e.g.:
* `NI_class_1_rate_1=0.12` (set the first bracket rate to 12%)
* `NI_class_1_threshold_2=50000` (set the second bracket threshold to 50k)
* `NI_class_1_num_brackets=4` (add enough brackets to have 4, break if the non-existing brackets' rates and thresholds are not passed)
* `NI_class_1_num_brackets=1` (remove all brackets above the first, modifying if rate or threshold is also passed)

**Comment by MaxGhenis** [comment]
Here's the design we came up with a couple days ago
<img width="701" alt="image" src="https://user-images.githubusercontent.com/6076111/157884956-6fc721a2-3072-4a2d-8d36-859111f4cd44.png">

**Comment by MaxGhenis** [comment]
This is becoming a more significant limitation, as we're using parameter scales more in openfisca-us. Parameter scales make code more concise and consistent, and I think we should refactor older code to use them more. Not adding to the sprint backlog just yet (I think the taxsim validation work is still more important), but adding a help wanted label in case anyone else wants to give it a shot.

**Comment by MaxGhenis** [comment]
[Example](https://docs.google.com/drawings/d/1uU8cJAcLOoYZbAyaiofJ210ru1r4YtvhdO2ae7EVwwo/edit?usp=sharing)

<img width="240" alt="image" src="https://user-images.githubusercontent.com/6076111/180269056-e647d1cf-3526-471d-9cb4-9d3c3c3aad99.png">

Potentially with a graph
