### ISSUE TITLE
`make install` throws react dependency conflict error

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#212]
Here's what I get when loading from `main` (or #208):
```shell
**(base) mghenis@penguin:~/PolicyEngine/policyengine$ make install
cd policyengine-client; npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: policyengine-client@1.1.4
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from react-router-ga@1.2.3
npm ERR! node_modules/react-router-ga
npm ERR!   react-router-ga@"^1.2.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mghenis/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mghenis/.npm/_logs/2021-11-28T05_45_53_907Z-debug.log
make: *** [Makefile:4: install-client] Error 1**
```
Looks to be from https://github.com/PolicyEngine/policyengine/blob/main/policyengine-client/package.json and https://github.com/fed/react-router-ga/blob/0f5f59aa24a965416848dd056abc08966f8e6389/package.json#L35

**Comment by MaxGhenis** [comment]
I changed the package.json to 16.8.6, but got this error instead:
```shell
(base) mghenis@penguin:~/PolicyEngine/policyengine$ make install
cd policyengine-client; npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: policyengine-client@1.1.4
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.8.6" from the root project
npm ERR!   peer react@">=16.0.0" from @ant-design/icons@4.7.0
npm ERR!   node_modules/@ant-design/icons
npm ERR!     @ant-design/icons@"^4.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-dom@17.0.2
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^17.0.2" from the root project
npm ERR!   peer react-dom@">=16.0.0" from @ant-design/icons@4.7.0
npm ERR!   node_modules/@ant-design/icons
npm ERR!     @ant-design/icons@"^4.7.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mghenis/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mghenis/.npm/_logs/2021-11-28T05_53_00_630Z-debug.log
make: *** [Makefile:4: install-client] Error 1
```

**Comment by nikhilwoodruff** [comment]
Strange - could you try deleting and re-cloning the repo? The GH action tests run the `npm install` routine, so maybe it's an old dependency stored somewhere.

**Comment by MaxGhenis** [comment]
Just deleted and re-cloned and got the same error.

**Comment by MaxGhenis** [comment]
@tolaouk is experiencing the same issue on a fresh clone

**Comment by nikhilwoodruff** [comment]
OK looking at this now, seems like a recently introduced issue - the GH action is now failing to run tests on 
#234 with the same message.

**Comment by nikhilwoodruff** [comment]
Found the issue - the GH action installs successfully when Node.js>=14.0.0-  @MaxGhenis @tolaouk could you check what version you have with `node -v`, and if it is pre-14 could you try upgrading?

**Comment by MaxGhenis** [comment]
I'm on node 14.15.1 and still get the error:
```
(base) mghenis@penguin:~/PolicyEngine/policyengine$ node -v
v14.15.1
(base) mghenis@penguin:~/PolicyEngine/policyengine$ make install
cd policyengine-client; npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: policyengine-client@1.1.4
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from react-router-ga@1.2.3
npm ERR! node_modules/react-router-ga
npm ERR!   react-router-ga@"^1.2.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mghenis/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mghenis/.npm/_logs/2021-12-03T18_37_16_654Z-debug.log
make: *** [Makefile:4: install-client] Error 1
```

**Comment by MaxGhenis** [comment]
Installing node 14.18.1, as used in the [GitHub Action](https://github.com/PolicyEngine/policyengine/runs/4408173883?check_suite_focus=true#step:4:9), resolved the react issue:
```shell
sudo npm cache clean -f
sudo npm install -g n
sudo n 14.18.1
```
Note that it didn't work with the latest stable version of node, which is 16.x.x.

I'm now getting a different error in #235 but closing this.

**Comment by MaxGhenis** [comment]
Actually looks like [`nvm`](https://github.com/nvm-sh/nvm#installing-and-updating) is the preferred tool for updating node, and updating to the latest version there also worked.
```shell
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
. ~/.bashrc
nvm install node
```
>v17.2.0 is already installed.
>Now using node v17.2.0 (npm v8.1.4)

**Comment by MaxGhenis** [comment]
Actually^2 the latest node version breaks `make debug-client`, so you should use `nvm install v14`.

**Comment by tolaouk** [comment]
Now I got these errors:

added 2741 packages from 1070 contributors and audited 2742 packages in 110.603s

274 packages are looking for funding
  run `npm fund` for details

found 13 vulnerabilities (8 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
pip install -e .
Obtaining file:///Users/tolaouk/PolicyEngine/policyengine
Collecting OpenFisca-UK==0.7.9
  Downloading OpenFisca_UK-0.7.9-py3-none-any.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB 4.1 MB/s 
ERROR: Could not find a version that satisfies the requirement OpenFisca-US==0.1.3 (from policyengine) (from versions: 0.0.3, 0.1.0, 0.1.1)
ERROR: No matching distribution found for OpenFisca-US==0.1.3
make: *** [install-server] Error 1
(base) tolaouk@Tolas-MacBook-Pro policyengine % npm audit
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tolaouk/.npm/_logs/2021-12-05T15_08_32_716Z-debug.log

**Comment by MaxGhenis** [comment]
Make sure to `conda activate py37`

**Comment by tolaouk** [comment]
Looks like it's working now.

**Comment by MaxGhenis** [comment]
> Actually^2 the latest node version breaks `make debug-client`, so you should use `nvm install v14`.

Further: I hit an error when v17 got installed by default. I could probably have gotten around it with `nvm activate v14` but instead I did `nvm deactivate node; nvm uninstall node; nvm activate v14` to avoid it moving forward.
