### ISSUE TITLE
Toggling abolish switches twice sets them to `abolish_x=0` instead of removing the provision

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#216]
For example, toggling Council Tax abolition twice produces this URL: http://policyengine.org/uk/population-impact?abolish_CT=0

and shows this:
![image](https://user-images.githubusercontent.com/6076111/143897344-bb27ce6d-b24c-41c6-b6d0-da6c7e59481b.png)

Same result with abolishing NI.

**Comment by nikhilwoodruff** [comment]
Fixed by https://github.com/PolicyEngine/policyengine/commit/e4e15904318b2376f790059004fc72c529f0de0a
