### ISSUE TITLE
Use version of LinkedIn logo without a square

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#22]

**Comment by Felix-Cadiz** [comment]
With our use of Ant Design, I believe this issue should be closed. If not, I can change the logo.

**Comment by MaxGhenis** [comment]
I'm still seeing the squares![Screenshot_20221102-174306.png](https://user-images.githubusercontent.com/6076111/199608386-967351a4-30db-4119-86ce-03b75d72ade3.png)
