### ISSUE TITLE
Add Marriage Allowance parameters

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#240]
- [ ] Cap as a percentage of the personal allowance (currently 10%)
- [ ] Abolition switch
- [ ] Make universal (@MaxGhenis?)

**Comment by MaxGhenis** [comment]
What do you mean by make universal?

Wouldn't setting the [parameter value](https://github.com/PolicyEngine/openfisca-uk/blob/master/openfisca_uk/parameters/tax/income_tax/allowances/married_couples_allowance/deduction_rate.yaml) from 10% to 0% effectively repeal it? Seems like that as a number, like the Personal Allowance, would suffice.

**Comment by nikhilwoodruff** [comment]
Sure on the repeal point- universality would be repealing the eligibility condition that requires the earner be paying the basic rate.

**Comment by MaxGhenis** [comment]
Sounds good - see https://github.com/PolicyEngine/openfisca-uk/issues/395 for a parameter with marriage allowance tax bands. We don't have a PolicyEngine component for list parameters yet, but I think something like checkboxes as buttons (like the chart button form of radio buttons) would look nice, especially given it's already an Enum.

**Comment by MaxGhenis** [comment]
Done
![image](https://user-images.githubusercontent.com/6076111/147605108-dc9f7ca3-8da2-4fc0-addc-7678dcd33704.png)
