### ISSUE TITLE
Add Resilience UBI

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#291]
As a branded reform

**Comment by MaxGhenis** [comment]
Done in [namedPolicies.jsx](https://github.com/PolicyEngine/policyengine/blob/main/policyengine-client/src/countries/uk/data/namedPolicies.jsx):

But @nikhilwoodruff could you remind me how the URL works? Neither https://policyengine.org/uk/population-impact/ubilabs/resilience-ubi nor https://policyengine.org/uk/population-impact&ubilabs/resilience-ubi works.

**Comment by nikhilwoodruff** [comment]
Whoops, OK fixed in https://github.com/PolicyEngine/policyengine/pull/304
