### ISSUE TITLE
Prevent users from setting non-monotonically-increasing thresholds

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#296]
For example this sets the additional threshold below the higher threshold: https://uk.policyengine.org/population-results?add_threshold=20000

It produces a surplus, but it's unclear what it's doing, so we should validate the threshold order.

**Comment by MaxGhenis** [comment]
Cool are we good to close this then? Or should we expand this issue to encompass the (not-yet-developed) component for tax brackets?

**Comment by nikhilwoodruff** [comment]
I think we can close this for now, yep
