### ISSUE TITLE
Remove `/year` from wealth parts of household questionnaire

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#344]
![image](https://user-images.githubusercontent.com/6076111/148833284-176df2be-635f-4b9d-8f07-3c987ff9a688.png)

**Comment by nikhilwoodruff** [comment]
WDYT of adding a metadata field to variables, specifying whether they are stocks or flows? We'd need to add some field like this, as I don't think we can derive this distinction from other metadata.

**Comment by MaxGhenis** [comment]
Right, specifying the period for wealth as ETERNITY wouldn't work right?

**Comment by nikhilwoodruff** [comment]
Yeah - plus, we need to uprate values.

**Comment by MaxGhenis** [comment]
We have the stock/flow metadata to do this now right?

**Comment by MaxGhenis** [comment]
done
