### ISSUE TITLE
Reorganize `About your household` sections

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#346]
I think we can get by without the expansions by making the sections:
* `General` + `Demographic/Family` + `Demographic/Household` -> `Household`
* `Demographic/Personal` -> `People`
* `Consumption/Family` + `Consumption/Household` -> `Consumption` (#345)

![image](https://user-images.githubusercontent.com/6076111/148834259-6151a91a-7b36-4315-8cd5-175f636cc77c.png)

**Comment by nikhilwoodruff** [comment]
Agree this is simpler, but some complication on the back end: currently, it's required that each page is exactly one entity type (this would also support multiple benefit units in the future). Could we keep family and household separate?

**Comment by MaxGhenis** [comment]
Fixed now per https://github.com/PolicyEngine/policyengine/issues/346#issuecomment-1010105471
