### ISSUE TITLE
`POLICYENGINE_SYNTH_UK=1 make debug server` throws `DefaultCredentialsError`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#368]
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

cc @tolaouk

**Comment by tolaouk** [comment]
yes this is resolved. @MaxGhenis
