### ISSUE TITLE
Local server issue

### ISSUE THREAD

**Issue by tolaouk** [PolicyEngine/policyengine#400]
TypeError: '>' not supported between instances of 'list' and 'float'
https://gist.github.com/tolaouk/d0177947a064ebf4dbab9115c7e037f0

**Comment by nikhilwoodruff** [comment]
Thanks for filing @tolaouk - just to check, is OpenFisca-UK (and PolicyEngine) definitely on the latest version? You can force this by running `make install-server`.

**Comment by MaxGhenis** [comment]
Has this been resolved?

**Comment by nikhilwoodruff** [comment]
I think so, but feel free to re-open @tolaouk if not.
