### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#444]
https://policyengine.org should be a friendly screen that points people most prominently to https://policyengine.org/uk, but also has our blog, about page, FAQ, social media, etc.

**Comment by ggordn3r** [comment]
@MaxGhenis you asked me to take a look at this issue and provide input on the new landing page. The pull request looks great. I think it could be even more effective with a clear mission statement at the top, a section describing PolicyEngine use cases in the middle, and a call-to-action at the end. The attached wireframe shows one idea. 

![PolicyEngine Landing Page Wireframe](https://user-images.githubusercontent.com/10144772/156457726-45ccc442-c027-420e-ab9b-d7d0ec3410b5.png)

**Comment by MaxGhenis** [comment]
I love this mock. Thank you @ggordn3r!

One example of the top section (mission+projects) is https://www.climateinteractive.org/en-roads. They reduce text and headings by putting the call to action in the button, using `>` to indicate entry, and making the hover super vibrant:
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6076111/156497488-70ec1d1e-f77d-4be7-a421-1baa6d956e5c.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/6076111/156497507-0a19061b-d5e1-4fe9-bf84-21c5cc62e2fd.png">

Similarly, the `Real World Examples` carousel made me think of the client logos platforms often show, e.g. on http://stripe.com:
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/6076111/156500144-62d096b8-addf-4bab-b47f-9eac44a3f4ca.png">

We don't have enough prominent users for that yet, but in the meantime we could put the blog posts in a carousel.
