### ISSUE TITLE
Shrink width of household table

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#488]
On my computer, my eyes have to travel a bit to get from the table row label to the number.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/6076111/153438297-0eb9b9e6-cd30-462c-8182-e3e1aa8f9225.png">

**Comment by nikhilwoodruff** [comment]
How's this? 
![image](https://user-images.githubusercontent.com/35577657/154734981-dcf4bf16-721f-4caa-98e0-2f88d333555a.png)
