### ISSUE TITLE
Shrink policy summary item vertical width

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#497]
Currently when the summary text goes over two lines, there's some too-large spacing: 
![image](https://user-images.githubusercontent.com/35577657/154233706-33dfe937-802d-45e2-bcc2-a5a55408b0af.png)

**Comment by Felix-Cadiz** [comment]
With the changes in the last few months, I believe this issue should be fixed. If we want to change the spacing, let me know.

Image attached for current reference.

![Screen Shot 2022-11-02 at 2 41 32 PM](https://user-images.githubusercontent.com/88756231/199607954-ff429fd5-fb98-49de-8806-fdf05b3e1434.png)
