### ISSUE TITLE
Toggling a policy switch on and off keeps it in the cart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#523]
For example, switching Child Benefit repeal on and then off produces this:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/6076111/156404901-6ccd91af-8c41-45bb-aff6-2982fc79feac.png">
And keeps it in the URL: https://policyengine.org/uk/population-impact?abolish_CB=0

This also occurs for all other switches I've tried.

**Comment by MaxGhenis** [comment]
Actually this is a bigger bug than aesthetics: After toggling it on, toggling it off doesn't actually toggle it off.
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/6076111/156419785-530c20c0-dc69-4325-b245-12a617073077.png">

**Comment by nikhilwoodruff** [comment]
After trialling a few fixes, I found one that worked in #521 . But this issue has come up a few times before, hopefully should be fixed for good now.
