### ISSUE TITLE
Selecting IRS / Income tax schedule in PolicyEngine US breaks the app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#543]
https://policyengine.org/us/policy
<img width="428" alt="image" src="https://user-images.githubusercontent.com/6076111/157749696-d76d3e07-3e4f-4391-ae41-ebc44cada01e.png">

**Comment by MaxGhenis** [comment]
Still broken

**Comment by nikhilwoodruff** [comment]
Still looking into this, it's a bit more complex than I thought (not sure why it re-broke, either)
