### ISSUE TITLE
Flags overlap on landing page on mobile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#571]
![Screenshot_20220323-180118.png](https://user-images.githubusercontent.com/6076111/159821398-92cc16de-fc05-4fc0-990d-9b301a231de8.png)

**Comment by nikhilwoodruff** [comment]
Adding spacing, and also ordering the biggest one first (US if in US, UK elsewhere) 
![image](https://user-images.githubusercontent.com/35577657/159947364-377c68c0-663b-4fd6-af4f-6c9b00ddd203.png)
