### ISSUE TITLE
Make flag buttons the same size on landing page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#572]
Seeing it more now live, I find the different sizes distracting. A couple people I asked also didn't find it intuitive that it was because of their location. We could try other approaches later but I'd opt for keeping it simple at this point.
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/6076111/159821574-77ecedfd-d791-450e-a5e6-6b0272bebbc4.png">

**Comment by nikhilwoodruff** [comment]
OK. Does any of this change now that we're ordering based off size?

**Comment by MaxGhenis** [comment]
Done
