### ISSUE TITLE
Update OpenFisca-Tools version to latest in setup.py

### ISSUE THREAD

**Issue by yuantaoz** [PolicyEngine/policyengine#670]
When I debug the server, I encounter the module not found error (openfisca-tools.data). I fixed it by uninstalling and updating to the latest version. 

So I think it might be a good option to update the requirements of openfisca-tools in setup.py, to prevent others having the same issue.

**Comment by MaxGhenis** [comment]
I think this is fixed now but feel free to reopen if you're still having an issue
