### ISSUE TITLE
`TypeError: unsupported operand type(s) for *: 'Role' and 'int'` when running local server

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#743]
When using the latest versions of openfisca-us and openfisca-tools. I think it's an openfisca-tools issue.

https://gist.github.com/MaxGhenis/d6cbb31be448ee18a156bc2faaf8fcac

**Comment by nikhilwoodruff** [comment]
Still not fully understanding all of the stack trace, but this error occurs when there's a missing group entity definition: in this case, because there are no defined `marital_unit` group entities.
