### ISSUE TITLE
[Resolved] Error running `make install-server`

### ISSUE THREAD

**Issue by mwufi** [PolicyEngine/policyengine#806]
This is just for people who run into trouble setting up `make install-server`!

Is there a foolproof way to set up the Python server? (or, like, the most foolproof way?)

I'm running into some issues with installing the package

For example:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/30219253/177428803-78806f39-877d-498f-8aca-2e2ae68c98ef.png">

The first thing you'll likely run into is installing the package `tables`. So, I did 

```
conda install pytables
```

Am I on the wrong track??

**Comment by mwufi** [comment]
You're probably right, it probably has something to do with my computer (M1 mac?)

Doing this works:
- Get a DigitalOcean droplet with Debian 11
- Install Miniconda ([like so](https://dev.to/waylonwalker/installing-miniconda-on-linux-from-the-command-line-4ad7))
- Create a new environment with python=3.7
- Install git + git clone the repo
- Run `make install-server`!

**Comment by mwufi** [comment]
If anyone is interested, I can make this an open devserver, so you can just ssh in & be ready to go!

**Comment by mwufi** [comment]
New update! We need to set up GOOGLE_APPLICATION_CREDENTIALS?

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/30219253/177675321-8cfd21c7-76a6-4647-b258-d7ca937d3946.png">

**Comment by nikhilwoodruff** [comment]
Hi @mwufi - so the reason you need GOOGLE_APPLICATION_CREDENTIALS is because some of the tests require a dataset that isn't fully public (UK data). We're working on a way to not run those tests where UK code hasn't been touched, but in the meantime we can only run those tests from branches on the repo.

**Comment by mwufi** [comment]
ah, gotcha! Is there a way to run a US-only version? (does `make debug-server` also depend on the UK data?)

**Comment by mwufi** [comment]
Great! I'm just commenting out UK for now :)

In `server.py`:
```
- countries: Tuple[Type[PolicyEngineCountry]] = (UK, US)
+ countries: Tuple[Type[PolicyEngineCountry]] = (US,)
```

**Comment by nikhilwoodruff** [comment]
Perfect, I occasionally do that just to save time, but yes that should work as an immediate solution.
