### ISSUE TITLE
Styling differences between local and live site

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#817]
I'm noticing some styling issues on the live site, which aren't reproducible locally (suggesting it's a library issue). Screenshots below.

### Local

![image](https://user-images.githubusercontent.com/35577657/178116249-fdee051c-52b2-4ba5-b68f-cc192a92786c.png)

### Live

![image](https://user-images.githubusercontent.com/35577657/178116253-b70561e4-0383-41f3-8c56-6caaeca68476.png)

### Local

![image](https://user-images.githubusercontent.com/35577657/178116266-62ebc516-0787-423f-acd1-1027cc7c81f1.png)

### Live

![image](https://user-images.githubusercontent.com/35577657/178116271-f6c404c0-1d8a-4c07-b070-2ef6102cf366.png)

**Comment by nikhilwoodruff** [comment]
Likely fixed by #820, will close after checking the live site when the deployments finish.

**Comment by MaxGhenis** [comment]
Verified!
