### ISSUE TITLE
Severe performance problems in US app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#839]
The US app takes 5-8 seconds to load on both desktop and mobile, and simulations take over two minutes. The UK app seems to be unaffected.
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/6076111/179363491-c87b7364-46cf-43f1-9819-e38696c32a0d.png">

[PageSpeed Insights](https://pagespeed.web.dev/report?url=https%3A%2F%2Fpolicyengine.org%2Fus) says reducing unused JS is the biggest opportunity.

**Comment by MaxGhenis** [comment]
I just kicked off a redeploy from the previous version: https://github.com/PolicyEngine/policyengine/actions/runs/2666122128

**Comment by MaxGhenis** [comment]
The redeploy failed because it can't publish to PyPI over an existing version. @nikhilwoodruff could you advise?

**Comment by nikhilwoodruff** [comment]
OK:
* To fix the redeploy failure, we need to modify the NPM publish action to ignore existing packages - there'll be a flag for it, I'll file a PR now.
* The problem will be server-side, not client-side. My best guess based on prior cases is that it's the county Enum taking up too much parameter space.

**Comment by MaxGhenis** [comment]
I'll file a new PR that basically reverts the previous one, downgrading openfisca-us and using the old MA parameter names.

**Comment by MaxGhenis** [comment]
Verified

**Comment by nikhilwoodruff** [comment]
Still investigating this - not as straightforward as I imagined. The core problem is that the `parameters` object rocketed to 145MB in size (!).

**Comment by nikhilwoodruff** [comment]
Aha - found at least part of it - the SLSPC costs were in the parameter endpoint. Implementing a quick fix so we can update PolicyEngine in the short term.
