### ISSUE TITLE
Handle -inf in parameter scales

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#866]
We need to use -inf in this one because it's on AGI

I think ideally it'd recognize it and just say "Below $100,000"

<img width="680" alt="image" src="https://user-images.githubusercontent.com/6076111/180872680-74fc0215-20ff-482d-9c01-5db3061d9046.png">

**Comment by MaxGhenis** [comment]
Ah this is also breaking the entry
<img width="453" alt="image" src="https://user-images.githubusercontent.com/6076111/180873088-dc1dce88-3ca6-4cf0-b85b-10d1d78897a9.png">

**Comment by MaxGhenis** [comment]
That workaround throws this server error, so I think we do need to parse it or change the current values to some large number:
>  File "/Users/maxghenis/PolicyEngine/policyengine/policyengine/utils/reforms.py", line 495, in create_reform
    description = get_summary(metadata, value)
  File "/Users/maxghenis/PolicyEngine/policyengine/policyengine/utils/reforms.py", line 416, in get_summary
    change_label = "Increase" if value > parameter["value"] else "Decrease"
TypeError: '>' not supported between instances of 'float' and 'str'

**Comment by nikhilwoodruff** [comment]
@MaxGhenis this does raise the question of how it should react to changes if we go with "below X"?

**Comment by nikhilwoodruff** [comment]
I'm going to go with making it uneditable

**Comment by MaxGhenis** [comment]
Does it update when changing the bottom threshold?

**Comment by nikhilwoodruff** [comment]
Yes

**Comment by MaxGhenis** [comment]
#865 didn't fix this. From the live app:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/6076111/181062703-060461f1-b739-42fa-9e48-d2d782fe7edb.png">
