### ISSUE TITLE
Several reforms are producing order-of-magnitude-off errors

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#903]
We have a major bug. Could be something with the baseline? We should probably shut off the app until we pin it down.

An empty reform is showing $10tn in impact: https://policyengine.org/us/population-impact

A minor Maryland reform is showing billions in impact (should be tens or hundreds of millions): https://policyengine.org/us/population-impact?md_cdcc_percent=0&md_non_single_childless_non_refundable_eitc_match=0&md_eitc_refundable_match=0&baseline_state_specific=MD

**Comment by nikhilwoodruff** [comment]
Just checked @MaxGhenis - both of these examples are now corrected for me ($0, and $228m).

**Comment by MaxGhenis** [comment]
This (or something like it) has resurfaced, e.g. [this reform that replaces SNAP/TANF/SSI with a $100/mo adult UBI](https://policyengine.org/us/population-impact?abolish_tanf=1&abolish_ssi=1&abolish_snap=1&young_adult_bi=1200&older_adult_bi_age=100&senior_bi_age=100) has a top-level budgetary impact way too high and misaligned with the budgetary impact chart. That chart also shows tax savings where none should exist.
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/6076111/184523095-e78b31a9-bd79-4bf6-92a5-7a484a736c21.png">

**Comment by MaxGhenis** [comment]
This link in https://github.com/PolicyEngine/policyengine/issues/903#issuecomment-1214285562 works correctly after making an unrelated update to PolicyEngine. But I'm leaving it open until we diagnose and fix it.

**Comment by MaxGhenis** [comment]
it's back - this occurred around 12:45pm PT
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/6076111/186988846-1c1ac6a3-d14b-46c0-b30c-9f10c1e4d2d4.png">

**Comment by MaxGhenis** [comment]
it's back
<img width="1764" alt="image" src="https://user-images.githubusercontent.com/6076111/188057716-51bdc44c-9b0c-4881-b3ec-21afe955f800.png">

https://policyengine.org/us/population-impact?ssi_amount_individual=13590&ssi_amount_couple=27180&ssi_flat_general_income_exclusion=128&ssi_flat_earned_income_exclusion=416
