### ISSUE TITLE
AutoUBI is mostly obscured on desktop

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#945]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/6076111/187041401-82ae2c62-33b9-476f-8c95-b82dda308d6d.png">

**Comment by Felix-Cadiz** [comment]
During standup, Nikhil and the team looked over this issue on the current deployed site in both US and UK servers. While there is some padding on the bottom, causing the AutoUBI to disappear before it reaches the footer, everything is accessible and viewable on desktop and mobile.
