### ISSUE TITLE
Can't page through policy provisions on mobile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#948]
This in the UK has two provisions, but only one is visible:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/6076111/187135359-428fdf51-5e57-41dd-a171-e20267cdb0b7.png">

Same happens on the US. On my phone (rather than the phone view on desktop) the second line of the provision also doesn't show up.

![Screenshot_20220828-231903.png](https://user-images.githubusercontent.com/6076111/187135662-2e7f3b8b-076c-4caf-82e5-7420fb7975c5.png)

**Comment by Felix-Cadiz** [comment]
With my latest push #1023, this issue should be fixed as well. The pagination is set to one item per page, let me know if we want to expand this.
