### ISSUE TITLE
Endless spinner in `Compute how earnings affect you` when toggling `bi_agi_limit_in_effect`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#963]
In #962 I added `bi_agi_limit_in_effect`. When flipping it, the population impacts and the net income table work properly, but the `Compute how earnings affect you` creates an endless spinner.

For example, clicking that button on this reform with a default household produces the error:
https://policyengine.org/us/household?older_adult_bi=1000&bi_agi_limit_in_effect=1&bi_agi_limit_amount_SINGLE=50000

That graph works fine with other policies.

**Comment by nikhilwoodruff** [comment]
I suspect this is also fixed by #966 : will close if so.

**Comment by MaxGhenis** [comment]
#966 fixed #964 but this is still broken

**Comment by MaxGhenis** [comment]
Thanks @nikhilwoodruff! Shows this now.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/6076111/188504794-b17d9bff-a7e0-49f1-a595-78e483fc9b36.png">
