### ISSUE TITLE
`Compute how earnings affect you` creates endless spinner for 21GI policy

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#964]
This reform describes the [Guaranteed Income for the 21st Century](https://drive.google.com/file/d/1UDFPwUYu2Rf4RGgXuOTacmBj2Gt9paAV/view) policy:
https://policyengine.org/us/population-impact?young_child_bi=4500&older_child_bi=4500&young_adult_bi=12500&older_adult_bi=12500&senior_bi=12500&bi_phase_out_threshold_HEAD_OF_HOUSEHOLD=10000&bi_phase_out_threshold_JOINT=15000&bi_phase_out_threshold_SEPARATE=10000&bi_phase_out_threshold_SINGLE=10000&bi_phase_out_threshold_WIDOW=10000&bi_phase_out_by_rate=0&bi_phase_out_end_HEAD_OF_HOUSEHOLD=50000&bi_phase_out_end_JOINT=70000&bi_phase_out_end_SEPARATE=50000&bi_phase_out_end_SINGLE=50000&bi_phase_out_end_WIDOW=50000

It works for the population impact and net income table, but not `Compute how earnings affect you`.

I'm not sure if it's the same issue as #963, since [this simulation](https://policyengine.org/us/household?older_adult_bi=1000&bi_phase_out_by_rate=0&bi_phase_out_end_SINGLE=50000) uses the similarly newly-introduced `bi_phase_out_by_rate` parameter by itself and it works fine. I haven't gone provision by provision yet to see what's causing the issue in 21GI.

**Comment by nikhilwoodruff** [comment]
OK it's an issue with the defined_for attribute, debugging.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff you tagged https://github.com/PolicyEngine/policyengine/commit/deca1c7dd08d46d5e3dc4b8594d8208de91bcaa2 in #965 as fixing this, but I just checked and it's still broken.

**Comment by nikhilwoodruff** [comment]
Huh, thanks. Let me see if I can reproduce it locally some other way (it works locally for me now).

**Comment by nikhilwoodruff** [comment]
OK I get this now (including with #966):
![image](https://user-images.githubusercontent.com/35577657/187954979-238f53bd-dd6b-4dea-965d-9fecbb4a53d2.png)
